package com.strategy;

import com.model.Point;

import java.util.Set;

public interface Strategy {

    /**
     * Implements the strategy, returning a {@link Set<Point>} given a number of required points and a bounding box.
     * @param n the number of points for the this strategy.
     * @param inputPoints a set of points generated by a previous strategy.
     * @param xmax the maximal x-coordinate of the bounding box. The minimal x-coordinate is assumed to be 0.
     * @param ymax the maximal y-coordinate of the bounding box. The minimal y-coordinate is assumed to be 0.
     * @return {@link Set<Point>}.
     */
    Set<Point> apply(int n, Set<Point> inputPoints, float xmax, float ymax);
}
